package com.tommyjohn.automation.PageLocators;

import org.openqa.selenium.By;

public class NavigationFlowPageLocators extends HomePageLocators
{			
	public static By MENS_ALL_NEWARRIVALS = SHOPALL_LINK;
	public static By WOMENS_ALL_NEWARRIVALS = SHOPALL_LINK;
	public static By ALL_MENS_SALE = SHOPALL_LINK;
	public static By MEN_SOCKS_ALLSOCKS = SHOPALL_LINK;
	public static By WOMEN_UNDERWEAR_ALLUNDERWEAR = SHOPALL_LINK;
		
	public static By MEN_UNDERWEAR_BOXERBRIEF = SECOND_lEVEL2_CATEGORY;
	public static By MEN_CLOTHING_TEESandPOLOS = FIRST_lEVEL2_CATEGORY;
	public static By WOMEN_BRAS_SCOOPBRALETTE = SECOND_lEVEL2_CATEGORY;
	public static By WOMEN_COLLECTION_COMFORTSMOOTHING = FIRST_lEVEL2_CATEGORY;
    public static By FINALSALE_WOMENSALE_UNDERWEAR = FIRST_lEVEL2_CATEGORY;
    
    public static By MEN_UNDERSHIRTS_VNECK = SECOND_lEVEL2_CATEGORY;
    public static By MEN_LOUNGEANDSLEEP_TOPS = SECOND_lEVEL2_CATEGORY;
    public static By MEN_SOCKS_CALF = SECOND_lEVEL2_CATEGORY;
    public static By WOMEN_UNDERWEAR_CHEEKY = SECOND_lEVEL2_CATEGORY;
    public static By FINALSALE_MENSALE_LOUNGEANDSLEEP = SECOND_lEVEL2_CATEGORY;
    
    public static By MEN_CLOTHING_BUTTONDOWNS = THIRD_lEVEL2_CATEGORY;
    public static By WOMEN_CLOTHING_DRESSES = THIRD_lEVEL2_CATEGORY;
    public static By WOMEN_LOUNGEANDSLEEP_PACKS = THIRD_lEVEL2_CATEGORY;
    
}
